name: Reproduction Materials

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v3"
      - name: Build Docker image.
        run: docker build -t gptools .
      - name: Generate figures.
        run: FAST=true ./in-docker.sh cook exec figures
